name: Build EXE

on:
 push:
   branches: [ "main" ]
 workflow_dispatch:

jobs:
 build:
   runs-on: windows-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Install SFML
     run: |
       curl -L -o sfml.zip https://github.com/SFML/SFML/releases/download/3.0.0/SFML-3.0.0-windows-vc17-x64.zip
       tar -xf sfml.zip -C C:\
       echo "SFML_DIR=C:\SFML-3.0.0\lib\cmake\SFML" >> $env:GITHUB_ENV
       echo "C:\SFML-3.0.0\bin" >> $env:GITHUB_PATH

   - name: Configure CMake
     run: cmake -B build -DCMAKE_BUILD_TYPE=Release

   - name: Build
     run: cmake --build build --config Release

   - name: Package EXE
     run: |
       mkdir package
       copy build\Release\*.exe package\
       copy build\Release\*.dll package\
       copy *.png package\
       copy C:\SFML-3.0.0\bin\*.dll package\

   - name: Upload artifact
     uses: actions/upload-artifact@v4
     with:
       name: Weldom-Game
       path: package\
